apiVersion: v1
kind: ImageStream
metadata:
  name: redhat-openjdk-18/openjdk18-openshift
  annotations:
    openshift.io/display-name: redhat-openjdk-18/openjdk18-openshift
spec:
  tags:
    - name: '1.0-4'
      annotations:
        openshift.io/display-name: redhat-openjdk-18/openjdk18-openshift
        description: >- 
          redhat-openjdk-18/openjdk18-openshift
        iconClass: icon-java 
        sampleRepo: 'https://github.com/clevandowski/spring-boot-hello-world' 
        tags: 'builder,java' 
        supports: 'java' 
        version: '1.0-4' 
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift'
